-- ============================================================================
-- Supabase Memory Layer Setup
-- Browser Automation Agent with RAG (Retrieval-Augmented Generation)
-- ============================================================================

-- Enable the pgvector extension for vector similarity search
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================================
-- User Profiles Table
-- Stores user information and preferences for personalized interactions
-- ============================================================================
CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username TEXT NOT NULL UNIQUE,
    personality_type TEXT,
    technical_level TEXT CHECK (technical_level IN ('beginner', 'intermediate', 'advanced', 'expert')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index on username for faster lookups
CREATE INDEX IF NOT EXISTS idx_profiles_username ON profiles(username);

-- ============================================================================
-- Memories Table for RAG
-- Stores user interactions, context, and learned patterns with vector embeddings
-- ============================================================================
CREATE TABLE IF NOT EXISTS memories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    embedding vector(768),  -- Google Gemini's embedding-001 produces 768-dimensional vectors
    metadata JSONB,  -- Optional: store additional context (page_url, action_type, etc.)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_memories_user_id ON memories(user_id);
CREATE INDEX IF NOT EXISTS idx_memories_created_at ON memories(created_at DESC);

-- Create vector index for fast similarity search using HNSW (Hierarchical Navigable Small World)
-- This dramatically speeds up nearest neighbor searches
CREATE INDEX IF NOT EXISTS idx_memories_embedding ON memories 
USING hnsw (embedding vector_cosine_ops);

-- ============================================================================
-- Function: Search Memories by Similarity
-- Uses cosine distance to find the most relevant memories for a given query
-- ============================================================================
CREATE OR REPLACE FUNCTION search_memories(
    query_embedding vector(768),
    match_user_id UUID,
    match_threshold FLOAT DEFAULT 0.7,
    match_count INT DEFAULT 10
)
RETURNS TABLE (
    id UUID,
    user_id UUID,
    content TEXT,
    metadata JSONB,
    similarity FLOAT,
    created_at TIMESTAMP WITH TIME ZONE
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        memories.id,
        memories.user_id,
        memories.content,
        memories.metadata,
        1 - (memories.embedding <=> query_embedding) AS similarity,
        memories.created_at
    FROM memories
    WHERE memories.user_id = match_user_id
        AND 1 - (memories.embedding <=> query_embedding) > match_threshold
    ORDER BY memories.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;

-- ============================================================================
-- Helper Function: Update timestamp trigger
-- Automatically updates the updated_at field when a profile is modified
-- ============================================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for profiles table
CREATE TRIGGER update_profiles_updated_at
    BEFORE UPDATE ON profiles
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- Optional: Function to insert memory with embedding
-- Convenience function for inserting memories (embedding would be generated by Gemini API)
-- ============================================================================
CREATE OR REPLACE FUNCTION insert_memory(
    p_user_id UUID,
    p_content TEXT,
    p_embedding vector(768),
    p_metadata JSONB DEFAULT '{}'::JSONB
)
RETURNS UUID
LANGUAGE plpgsql
AS $$
DECLARE
    new_memory_id UUID;
BEGIN
    INSERT INTO memories (user_id, content, embedding, metadata)
    VALUES (p_user_id, p_content, p_embedding, p_metadata)
    RETURNING id INTO new_memory_id;
    
    RETURN new_memory_id;
END;
$$;

-- ============================================================================
-- Optional: Function to get user context
-- Retrieves user profile along with recent memories
-- ============================================================================
CREATE OR REPLACE FUNCTION get_user_context(
    p_user_id UUID,
    recent_count INT DEFAULT 5
)
RETURNS JSON
LANGUAGE plpgsql
AS $$
DECLARE
    result JSON;
BEGIN
    SELECT json_build_object(
        'profile', (
            SELECT row_to_json(p)
            FROM (
                SELECT id, username, personality_type, technical_level, created_at, updated_at
                FROM profiles
                WHERE id = p_user_id
            ) p
        ),
        'recent_memories', (
            SELECT json_agg(m)
            FROM (
                SELECT id, content, metadata, created_at
                FROM memories
                WHERE user_id = p_user_id
                ORDER BY created_at DESC
                LIMIT recent_count
            ) m
        )
    ) INTO result;
    
    RETURN result;
END;
$$;

-- ============================================================================
-- Row Level Security (RLS) Policies
-- Uncomment these if you're using Supabase Auth
-- ============================================================================

-- Enable RLS on tables
-- ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE memories ENABLE ROW LEVEL SECURITY;

-- Allow users to read their own profile
-- CREATE POLICY "Users can view their own profile"
--     ON profiles FOR SELECT
--     USING (auth.uid() = id);

-- Allow users to update their own profile
-- CREATE POLICY "Users can update their own profile"
--     ON profiles FOR UPDATE
--     USING (auth.uid() = id);

-- Allow users to read their own memories
-- CREATE POLICY "Users can view their own memories"
--     ON memories FOR SELECT
--     USING (auth.uid() = user_id);

-- Allow users to insert their own memories
-- CREATE POLICY "Users can insert their own memories"
--     ON memories FOR INSERT
--     WITH CHECK (auth.uid() = user_id);

-- ============================================================================
-- Sample Data (Optional - for testing)
-- ============================================================================

-- Insert sample profile
-- INSERT INTO profiles (username, personality_type, technical_level)
-- VALUES ('demo_user', 'analytical', 'intermediate');

-- Note: Actual embedding insertion would be done through your application
-- after generating embeddings via OpenAI API

-- ============================================================================
-- End of Setup Script
-- ============================================================================

-- Verification queries (optional - comment out if not needed)
SELECT 'Setup completed successfully!' AS status;
SELECT COUNT(*) AS profile_count FROM profiles;
SELECT COUNT(*) AS memory_count FROM memories;
